apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-location-service
  name: app-location-service
spec:
  ports:
  - name: "5000-5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: app-location-service
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-location-service
  name: app-location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-location-service
  template:
    metadata:
      labels:
        app: app-location-service
    spec:
      containers:
      - image: chore05/app-location-service:latest
        name: app-location-service
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: TOPIC_NAME
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVER
      restartPolicy: Always