apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-persons-api
  name: app-persons-api
spec:
  ports:
  - name: "5000-30004"
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30004
  selector:
    app: app-persons-api
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-persons-api
  name: app-persons-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-persons-api
  template:
    metadata:
      labels:
        app: app-persons-api
    spec:
      containers:
      - image: chore05/app-persons-api:latest
        name: app-persons-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always