apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-location-collector
  name: app-location-collector
spec:
  ports:
  - name: "5005-30003"
    nodePort: 30003
    port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: app-location-collector
  type: NodePort


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-location-collector
  name: app-location-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-location-collector
  template:
    metadata:
      labels:
        app: app-location-collector
    spec:
      containers:
      - image: chore05/app-location-collector:latest
        name: app-location-collector
        imagePullPolicy: Always
        env:
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: TOPIC_NAME
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVER
      restartPolicy: Always